app:
  greeting:
    message: "Welcome"
    count: 3
    enabled: true
    services:
      - service1.url.com
      - service2.url.com
      - service3.url.com
    properties:
      prop1: Welcome
      prop2: 5
      prop: prpos
      val: some
  jdbc: true
  user:
    admin: "admin"
  name: "My-App"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: DEBUG
server:
  port: ${SERVER_PORT:8080}